### ISSUE TITLE
GADBannerViewDelegate not getting called

### ISSUE THREAD

**Issue by muhasturk** [dearhui/AdmobSwiftUI#2]
you should assign Coordinator as GADBannerViewDelegate to bannerView. delegate methods never get called.

**Comment by dearhui** [comment]
@muhasturk 
Thanks for the reminder about assigning the `Coordinator` as the `GADBannerViewDelegate` for the `bannerView`. Following your advice, I've made this change, and it's now correctly set up in version 1.2.2. Your guidance was invaluable in addressing this issue.
