### ISSUE TITLE
AdmobSwiftUI broken with 11.1.0 or newer / Xcode 15.3

### ISSUE THREAD

**Issue by talaviram** [dearhui/AdmobSwiftUI#3]
When trying to build under Xcode 15.3 and running on the simulator I get error ending up with:

`GoogleMobileAds.framework/Info.plist: No such file or directory`

I can enforce to add 11.0.1 (4668daa078c7e104df9f5b8a80a7638cab19bb4e) as additional package.
But then the app won't validate with AppStore, I suspect due to "older" binary not permitted?

<img width="603" alt="image" src="https://github.com/dearhui/AdmobSwiftUI/assets/6911158/8c57e5f1-7d38-47ef-87a8-928ff8f3d15c">

**Comment by NasrullahKhan** [comment]
I'm also facing the same issue.. @talaviram did you find any solution for this? below is the error i'm getting after successful compile

<img width="450" alt="Screenshot 2024-03-18 at 3 17 45 PM" src="https://github.com/dearhui/AdmobSwiftUI/assets/11390775/2edfd2c8-97b4-4d46-a7fe-3e2439771ec2">

**Comment by talaviram** [comment]
> did you find any solution for this? 

To run it, you can simply add:
[swift-package-manager-google-mobile-ads ](https://github.com/googleads/swift-package-manager-google-mobile-ads)
And state the specific commit or version (as I wrote above). That'll compile and work on simulator/devices. But, Validating the archive towards AppStore release won't work...

Additional note:
This also happens when just cloning this repo and running the Demo...
<img width="1512" alt="image" src="https://github.com/dearhui/AdmobSwiftUI/assets/6911158/d7cdd1fb-01b0-4e45-ade6-35d4c28615b3">

**Comment by talaviram** [comment]
I had to change the Admob dep. now it works. Until merged (hopefully), you can use my fork that does the job for me.

**Comment by dearhui** [comment]
@talaviram thanks
